services:
  app:
    build:
      context: .
    image: nextjs-dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true # Ensures file changes are detected in Docker
      DB_HOST: db        # Pass the db service name as an environment variable
    volumes:
      - .:/app:delegated         # Mount the current directory to the container
      - /app/node_modules        # Ensure node_modules remains in the container
    working_dir: /app            # Set the working directory inside the container
    command: npm run dev         # Start the development server

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db-1
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
